### ISSUE TITLE
problem with qt5.5 opengl and VC2013

### ISSUE THREAD

**Issue by afabri** [GillesDebunne/libQGLViewer#16]
In QGLViewer.pro I had to add  

LIBS += -lopengl32 -lglu32

in order to compile

**Comment by lrineau** [comment]
I can add information to Andreas' report. On Windows,  [Qt5 can use different OpenGL implementation][qt-wiki]: one uses the OpenGL implementation directly (from `opengl32.lib`), and the other uses the OpenGL provided by Angle.

[qt-wiki]: https://wiki.qt.io/Qt-5-on-Windows-ANGLE-and-OpenGL

Since Qt5.5, it seems that qt.io only provides the Windows installer for the version that uses Angle.

With that version, `opengl32.lib` and `glu32.lib` are no longer dependencies of the `QtGui` module. Thus we must link explicitly with them.
