### ISSUE TITLE
Modern openGL support planned?

### ISSUE THREAD

**Issue by CDitzel** [GillesDebunne/libQGLViewer#40]
I really like your project and the effort you have put into it.

Are you planning on porting it to modern openGL any time soon?

I am somehow reluctant to use legacy openGL which is required by the current libQGLViewer version

**Comment by GillesDebunne** [comment]
Hello,

This is a popular request, and it would make perfect sense. However, due to lack of time and knowledge, I unfortunately have no plans to work on this feature any time soon.

However, since this is an open source project, I'm open to contribution and would gladly provide help or advice to anyone willing to send a pull request. I have some ideas for a refactor, mostly along the lines of reducing the library's footprint.
