### ISSUE TITLE
GL_DEPTH_TEST disabled at the end of draw()

### ISSUE THREAD

**Issue by ataiya** [GillesDebunne/libQGLViewer#7]
Why is the depth buffer being disabled by qglviewer at the end of draw()?

With regards to this source (SHA 71831d839c25af808eb94d72264b7b74d6468742)
https://github.com/OpenGP/OpenGP/tree/qglviewer/apps/qglviewer

        void draw(){
    #ifdef FORCE_REENABLE_DEPTH
            glEnable(GL_DEPTH_TEST);
    #endif
            
            cout << __LINE__ << ": " << isDepthTestEnabled() << endl;        
            vao.bind();
            program.bind();
            cout << __LINE__ << ": " << isDepthTestEnabled() << endl;        
            {
                ///--- Update modelview
                setup_modelview(camera(), program);
                            
                ///--- clear & draw
                glClear(GL_DEPTH_BUFFER_BIT | GL_COLOR_BUFFER_BIT);
                glDrawElements(GL_TRIANGLES, triangles.size(), GL_UNSIGNED_INT, 0);
            }
            cout << __LINE__ << ": " << isDepthTestEnabled() << endl;        
            vao.release();
            program.release();
            cout << __LINE__ << ": " << isDepthTestEnabled() << endl << endl;        
        }

See this snapshot for the execution pattern. 
![screen shot 2014-06-25 at 2 05 19 pm](https://cloud.githubusercontent.com/assets/4480573/3385229/99707384-fc67-11e3-9bfd-e785c3e22ebe.png)

Note that I am using *Qt5/OpenGL4*, so perhaps this is something that will have to be stashed to be fixed in the future, but I thought it was worth reporting

**Comment by GillesDebunne** [comment]
Discovering your bug report just now. I must have missed a mail notification. Totally sorry about that.

This is probably the result of `postDraw()`, which is called automatically after your overloaded `draw()` method. It does disable `GL_DEPTH_TEST` since it may display overlays on screen. However, the entire block is protected by a `glPushAttrib(GL_ALL_ATTRIB_BITS);` which should ensure that the previous state is restored.

My guess is that it is related to OpenGL4, since the `glPushAttrib` is deprecated and may no longer properly do its job.

As a workaround, overload `postDraw()` by an empty method. If you need to display world axis, frame rate or others, copy paste some code from `postDraw()`.

**Comment by ataiya** [comment]
Yes, it's very likely because of deprecation. Really looking forward to the OpenGL4 version!
